### ISSUE TITLE
Rdf_uri.uri does not raise exception

### ISSUE THREAD

**Issue by ArnaudParant** [zoggy/ocaml-rdf#9]
Hello,

I notice few days ago that Rdf_uri.uri looks to not raise exception any more.
I tried several not uri value such "UK", "://", "://@#&(*&!".
I guess it's not normal ?

**Comment by zoggy** [comment]
I'm willing to drop the Rdf_uri module, to use OCaml-uri (https://github.com/mirage/ocaml-uri/). This will allow to run in browser with js_of_ocaml. Is this a problem ?
I cc @ArnaudParant too since Rdf_uri was used in sparql protocol modules.

By the way, I'm currently dropping the Rdf_iri module for the same reason. OCaml-rdf will use ocaml-iri  (https://github.com/zoggy/ocaml-iri/).
